language: node_js

node_js:
  - node

services:
  - docker

addons:
  sauce_connect: true

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-tag-1.37.36-64bit bash

before_script:
  - python -m SimpleHTTPServer &

script:
  - docker exec -it emscripten make deps all
  - node test-browser/runner --matrix test-browser/all.json
  - node_modules/.bin/mocha test-node

before_deploy:
  - rvm $(travis_internal_ruby) do ruby -S gem install octokit git
  - printf "//registry.npmjs.org/:_authToken=%s\n" "$NPM_TOKEN" >> ~/.npmrc

deploy:
  provider: script
  script: rvm $(travis_internal_ruby) do ruby -rubygems deploy.rb
  skip_cleanup: true
  on:
    tags: true
